name: valuhworld
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  introduction_screen: ^2.1.0
  country_picker: ^2.0.6
  flutter_snake_navigationbar: ^0.5.0
  modal_bottom_sheet: ^2.0.0
  location: ^4.3.0
  latlng: ^0.1.0
  measured_size: ^1.0.0
  firebase_auth: ^3.0.1
  cloud_firestore: ^2.4.0
  provider: ^5.0.0
  flutter_spinkit: ^5.0.0
  simple_animations: ^1.3.3
  firebase_core: ^1.4.0
  firebase_storage: ^10.0.1
  image_cropper: ^1.3.1
  image_picker: ^0.8.2
  time_ago_provider: ^4.1.0
  intl: ^0.17.0
  cached_network_image: ^3.1.0
  firebase_crashlytics: ^2.1.1
  image: ^3.0.2
  animator: ^3.1.0
  timeago: ^3.1.0
  geolocator: ^7.3.0
  uuid: ^3.0.4
  path_provider: ^2.0.2
  firebase_messaging: ^10.0.4
  flutter_svg:
  url_launcher: ^6.0.9
  flutter_paystack: ^1.0.5+1
  pay: ^1.0.5
#  flutter_map: ^0.13.1
  latlong2: ^0.8.0
  maps_launcher: ^2.0.1


  google_fonts: ^2.1.0
  font_awesome_flutter: ^9.1.0
  bubble: ^1.1.9+1

  fluttertoast: ^8.0.7
  purchases_flutter: ^3.3.1

#  Only in use depencies
  shared_preferences: ^2.0.6
  google_maps_flutter: ^2.0.6
  dio: ^4.0.0
  flutter_polyline_points: ^1.0.0





dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  fonts:
    - family: Signatra
      fonts:
        - asset: assets/fonts/Signatra.ttf

    - family: ArchivoNarrow
      fonts:
        - asset: assets/fonts/ArchivoNarrow-Bold.ttf
        - asset: assets/fonts/ArchivoNarrow-Regular.ttf


  assets:
    - assets/images/



